name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: npx nx-cloud record -- nx format:check

      - run: npx nx affected -t lint test build e2e-ci

      # - name: Automated Version Bump
      #   uses: phips28/gh-action-bump-version@v11.0.4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: npm run build:prod

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist
      #     path: dist/chuck-norris-joke-generator/browser

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/movie-search/browser # The folder the action should deploy.
          token: ${{ secrets.GH_TOKEN }} # The GitHub token.


      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     publish_dir: ./dist/movie-search/browser
